name: Feed Parser Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:

  deployDev:
      name: Dev deploy to ECR
      uses: ./.github/workflows/rw-build-image.yaml
      secrets:
        ecr-role: ${{ secrets.DEV_ECR_ROLE_TO_ASSUME }}
        ecr-region: ${{ vars.DEV_ECR_REGION }}
        ecr-repo: ${{ vars.DEV_ECR_REPOSITORY }}
        avature-feed-username: ${{ secrets.AVATURE_FEED_USERNAME }}
        avature-feed-password: ${{ secrets.AVATURE_FEED_PASSWORD }}
