name: Feed Parser Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
          
  deployDemo:
      name: Deploy image to Demo ECR repo
      uses: ./.github/workflows/rw-build-image.yaml
      secrets:
        ecr-role: ${{ secrets.DEMO_ECR_ROLE_TO_ASSUME }}
        ecr-region: ${{ vars.DEMO_ECR_REGION }}
        ecr-repo: ${{ vars.DEMO_ECR_REPOSITORY }}

  deployDev:
      name: Deploy image to Dev ECR repo
      uses: ./.github/workflows/rw-build-image.yaml
      secrets:
        ecr-role: ${{ secrets.DEV_ECR_ROLE_TO_ASSUME }}
        ecr-region: ${{ vars.DEV_ECR_REGION }}
        ecr-repo: ${{ vars.DEV_ECR_REPOSITORY }}

  deployStaging:
      name: Deploy image to Staging ECR repo
      uses: ./.github/workflows/rw-build-image.yaml
      secrets:
        ecr-role: ${{ secrets.STAGING_ECR_ROLE_TO_ASSUME }}
        ecr-region: ${{ vars.STAGING_ECR_REGION }}
        ecr-repo: ${{ vars.STAGING_ECR_REPOSITORY }}

  # deployProd:
  #     name: Deploy image to Prod ECR repo
  #     uses: ./.github/workflows/rw-build-image.yaml
  #     secrets:
  #       ecr-role: ${{ secrets.PROD_ECR_ROLE_TO_ASSUME }}
  #       ecr-region: ${{ vars.PROD_ECR_REGION }}
  #       ecr-repo: ${{ vars.PROD_ECR_REPOSITORY }}
