name: Feed Parser Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'main-test'

jobs:

  deployDemo:
      name: Demo deploy to ECR
      uses: ./.github/workflows/rw-build-image.yaml
      secrets:
        ecr-role: ${{ secrets.DEMO_ECR_ROLE_TO_ASSUME }}
        ecr-region: ${{ vars.DEMO_ECR_REGION }}
        ecr-repo: ${{ vars.DEMO_ECR_REPOSITORY }}

  deployDev:
      name: Dev deploy to ECR
      uses: ./.github/workflows/rw-build-image.yaml
      secrets:
        ecr-role: ${{ secrets.DEV_ECR_ROLE_TO_ASSUME }}
        ecr-region: ${{ vars.DEV_ECR_REGION }}
        ecr-repo: ${{ vars.DEV_ECR_REPOSITORY }}

  deployStaging:
      name: Staging deploy to ECR
      uses: ./.github/workflows/rw-build-image.yaml
      secrets:
        ecr-role: ${{ secrets.STAGING_ECR_ROLE_TO_ASSUME }}
        ecr-region: ${{ vars.STAGING_ECR_REGION }}
        ecr-repo: ${{ vars.STAGING_ECR_REPOSITORY }}

  deployProd:
      name: Prod deploy to ECR
      uses: ./.github/workflows/rw-build-image.yaml
      secrets:
        ecr-role: ${{ secrets.PROD_ECR_ROLE_TO_ASSUME }}
        ecr-region: ${{ vars.PROD_ECR_REGION }}
        ecr-repo: ${{ vars.PROD_ECR_REPOSITORY }}
