name: Resuable Workflow - Build and push image

on:
  workflow_call:
    secrets:
      ecr-role:
        required: true
      ecr-region:
        required: true
      ecr-repo:
        required: true

jobs:
  buildImage:
      name: Build and push image
      runs-on: ubuntu-latest
      permissions:
        id-token: write # This is required for requesting the JWT
        contents: read  # This is required for actions/checkout
      steps:
        # Checkout GitHub repository
        - name: Checkout
          uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

        # Assume role in Cloud Platform
        - name: Config Credentials
          uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
          with:
            role-to-assume: ${{ secrets.ecr-role }}
            aws-region: ${{ secrets.ecr-region }}

        # Login to container repository
        - name: Login to ECR
          uses: aws-actions/amazon-ecr-login@19d944daaa35f0fa1d3f7f8af1d3f2e5de25c5b7 # v2.1.4
          id: login-ecr
          with:
            mask-password: true
        - name: Build and Push FeedParser
          run: |
            docker build --pull --no-cache --tag $REGISTRY/$REPOSITORY:latest --file dockerfile .
            docker push $REGISTRY/$REPOSITORY:latest
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: ${{ secrets.ecr-repo }}
