name: Resuable Workflow - Build and push image

on:
  workflow_call:
    secrets:
      ecr-role:
        required: true
      ecr-region:
        required: true
      ecr-repo:
        required: true
      avature-feed-username:
        required: true
      avature-feed-password:
        required: true

jobs:
  buildImage:
      name: Build and push image
      runs-on: ubuntu-latest
      permissions:
        id-token: write # This is required for requesting the JWT
        contents: read  # This is required for actions/checkout
      steps:
        # Checkout GitHub repository
        - name: Checkout
          uses: actions/checkout@v4

        # Assume role in Cloud Platform
        - name: Config Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ secrets.ecr-role }}
            aws-region: ${{ secrets.ecr-region }}

        # Login to container repository
        - name: Login to ECR
          uses: aws-actions/amazon-ecr-login@v2
          id: login-ecr
          with:
            mask-password: true
        - name: Build and Push FeedParser
          run: |
            docker build --pull --no-cache --tag $REGISTRY/$REPOSITORY:latest --file dockerfile .
            docker push $REGISTRY/$REPOSITORY:latest
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: ${{ secrets.ecr-repo }}
            AVATURE_FEED_USERNAME: ${{ secrets.avature-feed-username }}
            AVATURE_FEED_PASSWORD: ${{ secrets.avature-feed-password }}
