name: Resuable Workflow - Build and push image

on:
  workflow_call:
    secrets:
      ecr-role:
        required: true
      ecr-region:
        required: true
      ecr-repo:
        required: true

jobs:
  buildImage:
      name: Build and push image
      runs-on: ubuntu-latest
      permissions:
        id-token: write # This is required for requesting the JWT
        contents: read  # This is required for actions/checkout
      steps:
        # Checkout GitHub repository
        - name: Checkout
          uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

        # Assume role in Cloud Platform
        - name: Config Credentials
          uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
          with:
            role-to-assume: ${{ secrets.ecr-role }}
            aws-region: ${{ secrets.ecr-region }}

        # Login to container repository
        - name: Login to ECR
          uses: aws-actions/amazon-ecr-login@183a1442edf41672e66566b7fc560e297a290896 # v2.1.1
          id: login-ecr
          with:
            mask-password: true
        - name: Build and Push FeedParser
          run: |
            docker build --pull --no-cache --tag $REGISTRY/$REPOSITORY:latest --file dockerfile .
            docker push $REGISTRY/$REPOSITORY:latest
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: ${{ secrets.ecr-repo }}
